export const en = {
    header: {
        contactUs: "Contact us",
        signUp: "Sign up"
    },
    home: {
        heroTitle: "How can we help you?",
        searchPlaceholder: "I want to...",
        searching: "Searching...",
        searchInstructions: "Use ↑↓ arrows to navigate, Enter to select |",
        viewFullResults: "View full results",
        breadcrumbHome: "Intelligence Hub",
        sidebarTitle: "Browse by topic",
        loading: "Loading...",
        noModules: "No modules found",
        loadingArticles: "Loading articles...",
        noArticlesInTopic: "No articles found for this topic",
        loadingTopics: "Loading topics...",
        noTopicsInModule: "No topics available for this module",
        allArticlesInModule: "All {module} Articles",
        noArticlesInModule: "No articles found for this module",
        moduleDescriptionFallback: "Discover guides and materials to empower your business with {app}.",
        waysToGetStarted: "Ways to get started",
        exploreApp: "Explore {app}",
        startGuide: "Start Guide",
        internalBanner: "Internal Help Center",
        knowledgeModules: "Knowledge Modules",
        exploreTopics: "Explore Articles"
    },
    search: {
        backToHome: "Back to Intelligence Hub",
        title: "Search Results",
        placeholder: "Search Intelligence Hub...",
        searching: "Searching...",
        noResults: 'No results found for "{query}"',
        enterQuery: "Enter a search query to see results",
        foundResults: "Found {count} result(s)",
        instructions: "Use ↑↓ arrows to navigate, Enter to select",
        loading: "Loading search...",
        inArticlePlaceholder: "Search in article...",
        foundInArticle: "{current} of {total} found",
        noResultsInArticle: "No results found in this article."
    },
    languages: {
        en: "English",
        zh: "中文"
    },
    article: {
        tableOfContents: "Table of Contents",
        generatingExcerpt: "Generating summary...",
        aiDisclaimer: "This response is generated by AI. AI can make mistakes.",
        aiSummaryTitle: "AI SUMMARY",
        expand: "Expand",
        collapse: "Collapse"
    },
    footer: {
        description: "Comprehensive documentation and resource center for Eva E-Commerce Intelligence.",
        resources: "Resources",
        hub: "Intelligence Hub",
        support: "Support",
        search: "Search",
        contactSupport: "Contact Support",
        language: "Language",
        allRightsReserved: "All rights reserved.",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service"
    }
};
