export const en = {
    header: {
        contactUs: "Contact us",
        signUp: "Sign up"
    },
    home: {
        heroTitle: "What would you like to explore today?",
        searchPlaceholder: "Search by topic or keyword...",
        searching: "Searching...",
        searchInstructions: "Use ↑↓ arrows to navigate, Enter to select |",
        viewFullResults: "View full results",
        breadcrumbHome: "Home",
        sidebarTitle: "Search by topic",
        loading: "Loading...",
        noModules: "No modules found",
        loadingArticles: "Loading articles...",
        noArticlesInTopic: "No articles found for this topic",
        loadingTopics: "Loading topics...",
        noTopicsInModule: "No topics available for this module",
        allArticlesInModule: "All {module} Articles",
        noArticlesInModule: "No articles found for this module",
        moduleDescriptionFallback: "Discover guides, courses, and materials to grow your business with {app}."
    },
    search: {
        backToHome: "Back to Home",
        title: "Search Results",
        placeholder: "Search articles...",
        searching: "Searching...",
        noResults: 'No results found for "{query}"',
        enterQuery: "Enter a search query to see results",
        foundResults: "Found {count} result(s)",
        instructions: "Use ↑↓ arrows to navigate, Enter to select",
        loading: "Loading search...",
        inArticlePlaceholder: "Search in article...",
        foundInArticle: "{current} of {total} found",
        noResultsInArticle: "No results found in this article."
    },
    languages: {
        en: "English",
        tr: "Türkçe",
        zh: "中文"
    },
    article: {
        tableOfContents: "Table of Contents",
        generatingExcerpt: "Generating summary...",
        aiDisclaimer: "This response is generated by AI. AI can make mistakes.",
        aiSummaryTitle: "AI SUMMARY",
        expand: "Expand",
        collapse: "Collapse"
    }
};
